//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer1119
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer1119()
        {
            this.Sale1119 = new HashSet<Sale1119>();
        }
    
        public int CustNo { get; set; }
        public string CustName { get; set; }
        public string CustAddr { get; set; }
        public Nullable<decimal> CustPostCode { get; set; }
        public string InterestCode { get; set; }
    
        public virtual Interest1119 Interest1119 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale1119> Sale1119 { get; set; }
    }
}
