//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale1119
    {
        public int CustNo { get; set; }
        public string RecordID { get; set; }
        public string Date { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Customer1119 Customer1119 { get; set; }
        public virtual Record1119 Record1119 { get; set; }
    }
}
